language: csharp
mono:
  - latest
  - 3.12.0
solution: solution-name.sln
script:
  - xbuild /p:Configuration=Release bank2qif.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Bank2QifTests/bin/Release/Bank2QifTests.dll